"""Diverging colormaps — two ramps meeting at a neutral midpoint.

Needed by heatmap-family charts whose data diverges around a meaningful centre
(docs/research/14-scope-recommendation.md lists "히트맵(시퀀셜/다이버징 팔레트 필요)").
Built by composing :func:`svgplot.palette.sequential.blend_sequence` twice, the same way
:func:`svgplot.palette.sequential.sequential` composes ``light_dark_sequence`` rather than
re-deriving an interpolation of its own.

Both registered maps take their two extremes from the Okabe-Ito colorblind-safe set, so a
reader with deuteranopia or protanopia can still tell the two directions apart — the whole
point of a diverging map is that direction carries meaning.
"""

from __future__ import annotations

from svgplot.palette._color import normalize_hex_color
from svgplot.palette.colorblind import BLOCKED_PALETTES
from svgplot.palette.sequential import blend_sequence

_NEUTRAL_MIDPOINT = "#f7f7f7"
"""Near-white centre shared by every registered map (ColorBrewer's diverging convention):
a light midpoint keeps both extremes dark enough to read as "far from centre", which a
mid-grey would blunt.
"""

DIVERGING_PALETTES: dict[str, tuple[str, str, str]] = {
    "coolwarm": ("#0072B2", _NEUTRAL_MIDPOINT, "#D55E00"),
    "purplegreen": ("#CC79A7", _NEUTRAL_MIDPOINT, "#009E73"),
}
"""Named diverging colormaps as ``(low, midpoint, high)`` triples."""


def diverging(name: str, n: int) -> list[str]:
    """Return ``n`` colors sampled from the named diverging colormap.

    Raises:
        ValueError: if ``name`` isn't a string, is in
            :data:`svgplot.palette.colorblind.BLOCKED_PALETTES`, or if ``n`` is negative.
        KeyError: if ``name`` isn't a registered diverging colormap.
    """
    if not isinstance(name, str):
        raise ValueError(f"palette name must be a string, got {name!r}")
    if name in BLOCKED_PALETTES:
        raise ValueError(f"palette {name!r} is blocked (perceptually non-uniform); use one of {sorted(DIVERGING_PALETTES)}")
    if name not in DIVERGING_PALETTES:
        raise KeyError(f"unknown diverging palette: {name!r} (available: {sorted(DIVERGING_PALETTES)})")
    if n < 0:
        raise ValueError(f"n must be non-negative, got {n}")
    low, midpoint, high = DIVERGING_PALETTES[name]
    return diverging_sequence(low, midpoint, high, n)


def diverging_sequence(low: str, midpoint: str, high: str, n: int) -> list[str]:
    """Ramp ``low -> midpoint -> high`` in ``n`` steps, symmetric about the midpoint.

    Symmetry is structural rather than incidental: both halves are generated by the same
    :func:`~svgplot.palette.sequential.blend_sequence` call shape with the same step
    count, so the k-th sample out from the centre sits at an identical interpolation
    fraction on either side.

    An even ``n`` has no sample sitting *on* the midpoint, so rather than shifting the
    two halves (which would break that guarantee) this builds the ``n + 1`` odd ramp and
    drops its centre — keeping both endpoints and leaving every surviving pair mirrored.
    """
    if n <= 0:
        return []
    if n == 1:
        # A single sample can only be the neutral centre; either extreme alone would
        # assert a direction the caller never chose.
        return [normalize_hex_color(midpoint)]
    odd_count = n if n % 2 else n + 1
    half = (odd_count + 1) // 2
    lower = blend_sequence(low, midpoint, half)
    upper = blend_sequence(midpoint, high, half)
    colors = lower + upper[1:]
    if n % 2 == 0:
        del colors[odd_count // 2]
    return colors
